### ISSUE TITLE
Listing 2017-2018 Technical Committee Leadership

### ISSUE THREAD

**Issue by michaelhayashi** [PurdueIEEE/old-IEEE-Website#109]
- **Aerial Robotics** needs to confirm current leadership and provide pictures and desired Purdue classification information
- **Computer Society** needs to update leadership to remove Shaurya and include Joven, Rebecca, Isha, and Sharan
- **EMBS** needs to rescale Kunal's picture and provide pictures for Danay, Cyril's replacement, and Barnabas (Purdue classification information also needed)
- **MTT-S** needs to get a picture for Rayane
- **Racing** needs to confirm expanded leadership and provide pictures and desired Purdue classification information
- **ROV** needs to upload a team picture for the 2017-2018 season

**Comment by erikvanderwerf** [comment]
I'm closing this since it's probably outdated.
