### ISSUE TITLE
404 Error for ROV _Cephalopod_ Press Releases

### ISSUE THREAD

**Issue by michaelhayashi** [PurdueIEEE/old-IEEE-Website#110]
The page https://purdueieee.org/rov/history/cephalopod.php does not exist. There needs to be a PHP page written that has all of the press releases for the 2016-2017 ROV season aggregated on it.

**Comment by erikvanderwerf** [comment]
This page still does not exist. Is this a page that we would like to make? @michaelhayashi

**Comment by michaelhayashi** [comment]
@grantg012 It looks like the hyperlink was removed from the ROV history page that caused the 404 error. Unless you want to dig through the old press releases from Kyle Rakos' final year, should we close this issue?
