### ISSUE TITLE
Update Committee Pages

### ISSUE THREAD

**Issue by erikvanderwerf** [PurdueIEEE/old-IEEE-Website#123]
From Meeting 02. Not sure what to update for most of them but when I get around to it I'll ask in the Slack.

MTT-S put a document in the Secretary folder with a list of requested changes.

**Comment by michaelhayashi** [comment]
@SwagatBhattacharyya What is your opinion about how up to date the committee pages are for IEEE? We might be able to close this issue thanks to what Grant and you have done this year.

**Comment by grantg012** [comment]
Yeah I think we can close this
