### ISSUE TITLE
Modernize the About Page

### ISSUE THREAD

**Issue by michaelhayashi** [PurdueIEEE/old-IEEE-Website#201]
The about page was something I spun together quickly when we first transitioned from Drupal CMS to our Bootstrap HTML/PHP solution for the Purdue IEEE website. It gets the job done but improvements from more perspectives would be nice. Good examples are Purdue HKN (https://engineering.purdue.edu/hkn/pages/history.php) and UIUC IEEE Student Branch (https://ieee.illinois.edu/about/).

We should probably explain what Cornerstones committees are explicitly on the about page (the term itself was too new at the time to use). We can upload some of the historical documents that the past Secretaries maintained. Some investigative journalism might be warranted.

**Comment by hadiahmed098** [comment]
I think this can be closed with PurdueIEEE/IEEE-Website@36ef8c9
