### ISSUE TITLE
Site looks slightly dated in its design and layout

### ISSUE THREAD

**Issue by hadiahmed098** [PurdueIEEE/old-IEEE-Website#204]
This is also in the same vein as  #201, but the color scheme most of the pages currently use is the default Bootstrap scheme. In comparison to the sites of some nearby universities, ours should reflect Purdue colors. While the blue does represent IEEE, it does not bring Purdue to mind. We may need to (a) edit the default Bootstrap stylesheet (as some committees have) or (b) write our own style framework. 

Second, there is no cohesive design to most sub pages. There are 11 committee pages and 4-5 distinct layouts used. Uniformity may not be perfect, but it does seem more professional. I agree with #200 that much of the information like social media, join links, etc is hidden on the bottom of sub pages. This is a problem with most committees, however, and not just the main page. Trying to find emails, join information, or other social media can be nearly impossible.

Finally, this may be a bit out there, but is there any particular reason we are using PHP? Most of the functions of PHP the website uses could probably be rewritten or simplified in JavaScript (JSON and arrays come to mind). The one useful feature I think PHP uses is the <? include ?> statements.

Some examples to consider:
[UIUC](https://ieee.illinois.edu/) - I think this one is quite good
[UW-Madison](https://ieee.slc.engr.wisc.edu/)
[UIowa](https://ieee.org.uiowa.edu/)
[OSU](https://ieee.osu.edu/)

**Comment by hadiahmed098** [comment]
As another aside, the 'Officers' page can get confusing as it goes by calendar year while officer terms go by academic year. Perhaps we should organize the tabs like ['2018-19', '2019-20', '2020-21', etc.]?

**Comment by grantg012** [comment]
It might be worth moving the officers thing to a new issue. It'll require some thorough renaming. It'll also be a shorter fix that one of us can make pretty quickly

**Comment by hadiahmed098** [comment]
Good point, created #205.

**Comment by hadiahmed098** [comment]
I think this can be closed with PurdueIEEE/IEEE-Website@36ef8c9
