### ISSUE TITLE
Officer page can be reorganized

### ISSUE THREAD

**Issue by hadiahmed098** [PurdueIEEE/old-IEEE-Website#205]
The current officer page displays the officers through a calendar year, while officer terms are from June through May. For example, 2019 has a lot of parenthetical to denote the reorganization. I see two solutions for this:

1. Change the labeling from 2018, 2019, 2020 to 2018-19, 2019-20, 2020-21
2. Keep the current calendar year, but add a 'Spring' and 'Fall' tab.

I think 2 would be a better solution, but we would need to rewrite large parts of the code we use for the officer page. Option 1 is simpler.

**Comment by grantg012** [comment]
I’m in favor of option 1. Will make it a little easier to navigate by not having a spring and fall to flip between
