### ISSUE TITLE
Convert pages to Markdown and realtime parse them

### ISSUE THREAD

**Issue by avaidyam** [PurdueIEEE/old-IEEE-Website#44]
Migrate all the user-facing/constantly updated pages from PHP into Markdown and use [this PHP module](http://parsedown.org) to parse them to HTML in realtime. It lends to maintainability.

**Comment by mattmolo** [comment]
I don't like this. Duplicates pretty much all webpages.

**Comment by avaidyam** [comment]
It doesn't technically, we'd need one PHP script and some Apache magic to allow it to intercept `purdueieee.org/my_page` and secretly execute `purdueieee.org/translate?page=my_page`, giving us the output.

The `translate.php` script would look to see if any such markdown file exists, and then spit it out, otherwise, 404 that bad boy.

**Comment by avaidyam** [comment]
This is one project I'm okay with working on instead since I wanted to do this since last year.

**Comment by mattmolo** [comment]
Ignore those commits above... :|
