### ISSUE TITLE
Add padding to web pages

### ISSUE THREAD

**Issue by mattmolo** [PurdueIEEE/old-IEEE-Website#53]
Constitution has `col-lg-8 col-lg-offset-2` on the main page body. On wide screens it keeps it to a nice small width, easy to read, etc. On smaller screens it is responsive and fills the whole width. Some pages are lacking this, such as dues, about and some committee pages.

Suggest to add this in. (I will do)

**Comment by avaidyam** [comment]
Please take care of this along with the rest of the fixes if you can!
