### ISSUE TITLE
BIG BIG ISSUE

### ISSUE THREAD

**Issue by Sophiaduan** [PurdueIEEE/old-IEEE-Website#65]
https://github.com/PurdueIEEE/IEEE-Website/blob/master/learning/index.php#L106
Time: Friday, Sept.30, Phys 223, 6-8pm
Mentors: Prof.Lu, Aditya, Brandon
Helpers: Yuqin, Ben, Sid, Justin, Michael

Also please at somewhere mention this github is something with prof.Lu and his ECE 264 class

**Comment by stwrt** [comment]
It's not that big of an issue.

**Comment by avaidyam** [comment]
@Sophiaduan Next time, just send it to one of us in Slack.

**Comment by mattmolo** [comment]
@avaidyam I told her to make an issue..

**Comment by avaidyam** [comment]
Oh, is that what we're doing now? @Sophiaduan you're good. 👍
