### ISSUE TITLE
CSociety Needs More Information

### ISSUE THREAD

**Issue by stwrt** [PurdueIEEE/old-IEEE-Website#79]

**Comment by avaidyam** [comment]
No it doesn't

**Comment by stwrt** [comment]
I disagree

**Comment by exponentialbit1024** [comment]
We are a group of highly curious people with quirks in the science of computation. We do cool stuff with computers and try to spread the enlightenment with who-so-ever matches the level of curiosity of the group. 3D printing, web developing, cyber security, high performance computing, machine learning, graphics and everything you've heard of as tech-y is discussed, talked and made here, feel free to drop by?

**Comment by stwrt** [comment]
This works

**Comment by exponentialbit1024** [comment]
want to add pictures of the Exec team now that we have 4?
