### ISSUE TITLE
Updates for IEEE MTT-S

### ISSUE THREAD

**Issue by michaelhayashi** [PurdueIEEE/old-IEEE-Website#80]
Check the Slack posts on January 20 for updates to MTT-S materials

**Comment by stwrt** [comment]
Please put what was discussed on January 20th in Slack on here.

**Comment by michaelhayashi** [comment]
https://purdueieee.slack.com/messages/ieee-infrastructure/
The discussion in question is a subset of what can be found at this link

**Comment by stwrt** [comment]
Please post the exact text here

**Comment by michaelhayashi** [comment]
The Aerial Robotics, EMBS, MTT-S, and Racing committee pages need updating for the contact or leadership shown. May the MTT-S page please get updated with officer bubbles like PARTIEEE page has? The default color scheme works for me.

The MTT-S logo should be on the committee page as well. 

This image should be part of the carousel 

Also super important, please make sure that MTT-S gets a sponsor page going that lists the sponsorship tiers (top-to-bottom: Terahertz-energy Partner, Microwave-energy Partner, and Radio-energy Partner) and puts the Bechtel Corporation logo under Radio-energy Partner

**Comment by michaelhayashi** [comment]
[04-WebSafe-ForWeb-Hex.zip](https://github.com/PurdueIEEE/IEEE-Website/files/738120/04-WebSafe-ForWeb-Hex.zip)

**Comment by michaelhayashi** [comment]
![mtt-s_fourth_meeting_ivory_soap_720](https://cloud.githubusercontent.com/assets/3538398/22411771/6aec832c-e675-11e6-8d4b-23782c0bd70a.jpg)

**Comment by michaelhayashi** [comment]
May the MTT-S page please get updated with officer bubbles like PARTIEEE page has?
