### ISSUE TITLE
New Pages for MTT-S

### ISSUE THREAD

**Issue by michaelhayashi** [PurdueIEEE/old-IEEE-Website#87]
May the main MTT-S page please get updated with officer bubbles like PARTIEEE page has?
- MTT-S Chair: Michael Hayashi (3rd Year Graduate, Electrical and Computer Engineering)
- MTT-S Vice Chair: Michael Anderson (Junior, Industrial Engineering)
- MTT-S Sponsorship Coordinator: AVAILABLE
- MTT-S Workshop Coordinator: AVAILABLE
- MTT-S Event Coordinator: Alan Han (Junior, Electrical Engineering)

May MTT-S also get a subsidiary sponsors page just as ROV does?
- Terahertz-energy Partners: NONE
- Microwave-energy Partners: Northrop Grumman Corporation
- Radio-energy Partners: Bechtel Corporation

May MTT-S also get a subsidiary bylaws page just as ROV does?

**Comment by michaelhayashi** [comment]
Use Michael Hayashi photo on 2016 officers page.
Michael Anderson photo: ![michaelanderson_9-12-16](https://cloud.githubusercontent.com/assets/3538398/22994006/219a5552-f393-11e6-817b-82d434f81913.JPG)

**Comment by michaelhayashi** [comment]
Alan Han photo: 
![picture](https://cloud.githubusercontent.com/assets/3538398/23052828/6dc63f62-f4a2-11e6-956f-05452aee34f3.jpg)

**Comment by stwrt** [comment]
Partially Complete

**Comment by avaidyam** [comment]
What's my role with this PR, @brstew?

**Comment by stwrt** [comment]
Sponsors Page added.
