### ISSUE TITLE
Move all committee bylaws to the Const. page

### ISSUE THREAD

**Issue by avaidyam** [PurdueIEEE/old-IEEE-Website#95]
Add tabs to the page and just put all the constitution, legislation, and committee bylaws documents in one spot.

**Comment by stwrt** [comment]
When you say legislation I assume you mean all votes in exec meetings. Also, there should be a link to all Meeting Minutes too.

**Comment by avaidyam** [comment]
Yes and yes.

**Comment by avaidyam** [comment]
@hadiahmed098 Nice work!
